// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mxNJ84M-j1unTmh7G3McrSAil3t_7kI',
    appId: '1:1084601339826:web:2b95505950d3888a571eab',
    messagingSenderId: '1084601339826',
    projectId: 'movie-app-23850',
    authDomain: 'movie-app-23850.firebaseapp.com',
    storageBucket: 'movie-app-23850.firebasestorage.app',
    measurementId: 'G-J9X78RSG20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMo2kVHliEWtPbXzeIgtcAsuReOTX8FRc',
    appId: '1:1084601339826:android:93a5b4d0248c8c0b571eab',
    messagingSenderId: '1084601339826',
    projectId: 'movie-app-23850',
    storageBucket: 'movie-app-23850.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyk55nWjNz6nVWiSpTmOTd_3WKkdsuGpI',
    appId: '1:1084601339826:ios:e5d41098224ba013571eab',
    messagingSenderId: '1084601339826',
    projectId: 'movie-app-23850',
    storageBucket: 'movie-app-23850.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );
}
