import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'app.dart';
import 'core/di/injector.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // `firebase_options.dart` is generated by `flutterfire configure` — never
  // hand-edit it. Re-run that command if a platform is added.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  await setupInjector();

  runApp(const MovieApp());
}
